# Merge dev branch to test
name: Sync Branches
on: 
  push:
    branches: 
      - dev
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
         git config --local user.email "githubactions@noreply.com"
         git config --local user.name "githusuer"
    - name: Merge dev back to test
      run: |
          git fetch --unshallow
          git checkout test
          git pull
          git merge --no-ff origin/dev -m "Auto-merge dev back to master"
          git push
