# Deploy Packages to test sevrer 
on: 
  push:
    branches: 
      - 'dev'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ","
        
    - name: List all added files
      id: modified      
      run: | 
        echo "modifiedfiles=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_ENV
        #echo "modifiedfiles"
        echo "${{ secrets.REMOTE_USER }}"
        
    - name: Execute Shell Script
      env:
        remoteUser: ${{ secrets.REMOTE_USER }}
        remoteHost: ${{ secrets.REMOTE_SERVER }}
        remotePATH: ${{ secrets.REMOTE_PATH }}
      run: |
        echo "$modifiedfiles"
        chmod +x ./remote_copy.sh
        ./remote_copy.sh
