# sync branches
on: 
  push:
    branches: 
      - dev
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ","
        
    - name: List all added files
      id: modified
      run: |        
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "modifiedfiles=$file" >> $GITHUB_ENV 
          #dir=$(dirname "$file"); 
          #echo "$file was added"; 
          #echo "Directory: $dir";
          #BASE_DIRECTORY=$(echo "$dir" | cut -d "/" -f1);
          #echo "$BASE_DIRECTORY";
        done
        chmod +x remote_copy.sh
        ./remote_copy.sh
