name: Sync Branches
on:
  push:
    branches:
      - dev
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: master
          message: Merge dev into master
          github_token: ${{ secrets.GITHUB_TOKEN }}
