# Merge dev branch to master
name: Sync Branches
on: 
  push:
    branches: 
      - dev
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
         git config --local user.email "githubactions@noreply.com"
         git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff origin/master -m "Auto-merge master back to dev"
          git push
       
