#Sync Branches
name: Sync Branches
on: 
  push:
    branches: 
      - dev
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "sandeep.bikkina@ah.nl"
          git config --local user.name "Sandeep084b"
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Merge master back to dev
      run: |
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff origin/master -m "Auto-merge master back to dev"
          git push
