name: Sync Branches
on: 
  push:
    branches: 
      - dev
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff origin/master -m "Auto-merge master back to dev"
          git push
