# Merge dev branch to test
name: Sync Branches
on: 
  push:
    branches: 
      - dev
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ","
        
    - name: List all added files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was added"
        done
    - name: Set Git config
      run: |
         git config --local user.email "githubactions@noreply.com"
         git config --local user.name "githusuer"
    - name: Merge dev back to test
      run: |
          git fetch
          git checkout test
          git pull
          git merge --no-ff origin/dev -m "Auto-merge dev back to master"
          git push
